services:
  redis:
    container_name: content-finder.redis
    image: redis:7.4.2
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    restart: on-failure
  content-finder:
    container_name: content-finder.bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      COMMAND_SYMBOLS: "!,$$,/"
      CYTUBE_URL: https://cytu.be
      CYTUBE_URL_CHANNEL_NAME: ${CYTUBE_URL_CHANNEL_NAME}
      CYTUBE_USERNAME: ${CYTUBE_USERNAME}
      CYTUBE_PASSWORD: ${CYTUBE_PASSWORD}
      CYTUBE_MSG_LIMIT: 320
      VALID_TAGS: ${VALID_TAGS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      LOG_LEVEL: DEBUG
    depends_on:
      redis:
        condition: service_healthy
    restart: on-failure

volumes:
  redis:
