FROM python:3.10-slim-buster

WORKDIR /app

RUN python -m pip install black \
    && python -m pip install isort \
    && echo "#!/bin/bash" > formatter.sh \
    && echo "black --skip-string-normalization /app/cytubebot/" >> formatter.sh \
    && echo "isort cytubebot tests" >> formatter.sh \
    && chmod +x formatter.sh

CMD ["./formatter.sh"]